### ISSUE TITLE
Product Page - FRONT END

### ISSUE THREAD

**Issue by Rafflafressia** [Rafflafressia/Star-Inventory-Logistics#10]
This page should render a series of cards with product names and images so that when a user clicks on the card it takes them to the product description page with the associated data

**Comment by MohnishBhujun** [comment]
Created product page handlebar, will polish


![Image](https://github.com/Rafflafressia/Star-Inventory-Logistics/assets/149837818/cd9d109d-912c-4995-b043-61529dc4d1fa)



![Image](https://github.com/Rafflafressia/Star-Inventory-Logistics/assets/149837818/2185ab16-8ef1-4263-8401-be5ee7557524)

**Comment by Rafflafressia** [comment]
Hey Mohnish, that's a great start! Let's work together to separate some of those scripts and the html!

**Comment by MohnishBhujun** [comment]
Here is a better version.



![Image](https://github.com/Rafflafressia/Star-Inventory-Logistics/assets/149837818/9d313e54-d5d0-4c03-92b5-7bfd58d1eb63)



![Image](https://github.com/Rafflafressia/Star-Inventory-Logistics/assets/149837818/d92cc2b5-1ee2-4f9d-aa8c-cba5631c6792)

**Comment by Rafflafressia** [comment]
Changes: 

- [x] Add on click function to render product description
- [x] Add button to go back to product page
- [x] Render categories and product names in accordion search bar appropriately

I'll be working on these changes 
- Arkaw
