### ISSUE TITLE
Manager Settings Page - FRONT END

### ISSUE THREAD

**Issue by Rafflafressia** [Rafflafressia/Star-Inventory-Logistics#11]
This page will have two buttons: 

One to go to Add/Update Products

One to Add Employees

**Comment by MohnishBhujun** [comment]
Created the page and css



![Image](https://github.com/Rafflafressia/Star-Inventory-Logistics/assets/149837818/acc2e8eb-cd18-46e6-b2cc-955bce6bd25d)
