### ISSUE TITLE
Add Employee Page - FRONT END

### ISSUE THREAD

**Issue by Rafflafressia** [Rafflafressia/Star-Inventory-Logistics#12]
This page should have several input fields for first name, last name, position in the company and a username that will be assigned by the managers (format for this will always be FirstnameLn i.e JasonG)

**Comment by MohnishBhujun** [comment]
Created Employee handlebar and css



![Image](https://github.com/Rafflafressia/Star-Inventory-Logistics/assets/149837818/2f00f710-ec80-49ee-8200-2641999904f8)



![Image](https://github.com/Rafflafressia/Star-Inventory-Logistics/assets/149837818/d9b64a4a-79fe-4290-9fac-c1da6b90b71a)

**Comment by MohnishBhujun** [comment]
The changes for this are in pull request "SIL Homepage - 44"
