### ISSUE TITLE
Setup Authorization (with bcrypt) - API ROUTE

### ISSUE THREAD

**Issue by Rafflafressia** [Rafflafressia/Star-Inventory-Logistics#22]
Setup backend logic for when a user inputs their username and password.

**Comment by Jason897571** [comment]
# Need to set up auth middleware for the router below:

## HomeRouters & managerRouters: (Regarding front end rendering)

- [ ] /product-detail (both **employee** and **manager** have access)

- [ ] /manager/manage-option (only **manager** has access)
- [ ] /manager/manage-option/product-related  (only **manager** has access)
- [ ] /manager/manage-option/productRelated/add-product  (only **manager** has access)
- [ ] /manager/manage-option/productRelated/search-product  (only **manager** has access)
- [ ] /manager/manage-option/add-employee  (only **manager** has access)

## API router: (Regarding back end receiving request from front end)

### --------------------Category API---------------------
- [ ] /api/categories (method: GET, get all category info)
### --------------------Product API---------------------
- [ ] /api/products (method: GET, get all product info)
- [ ] /api/products/:id (method: GET, get single product info)
- [ ] /api/products (method: POST, create single product info)
- [ ] /api/products/:id (method: PUT,update single product info)
- [ ] /api/products/:id (method: DELETE,delete single product info)
### --------------------Add Employee API---------------------
- [ ] /api/add-employee (method: POST, create single employee info)
- [ ] optional: update and delete info for an employee
