### ISSUE TITLE
FRONT END USER STORY - README

### ISSUE THREAD

**Issue by Rafflafressia** [Rafflafressia/Star-Inventory-Logistics#6]
- [ ] 1) Login Page 
- [ ] 2) Products Page
- [ ] 3) Manager Settings
- [ ] 4) Add Employee Page
- [ ] 5) Add/Update Product Page *(search) 
- [ ] 6) Product Description Page

**Comment by MohnishBhujun** [comment]
Creating the UI from FIGMA Base

![Screenshot 2024-03-04 185802](https://github.com/Rafflafressia/Star-Inventory-Logistics/assets/149837818/5425a1c5-eef4-464f-8331-b56bcb0bb979)
