### ISSUE TITLE
Setup Home Routers

### ISSUE THREAD

**Issue by Rafflafressia** [Rafflafressia/Star-Inventory-Logistics#7]
set up the home routers structure to link to handlebars files

**Comment by Jason897571** [comment]
HomeRoutes
  - [x] login
  - [x] product details
  - [x] homerouter (as /)

mangerRoutes
  - [x] manage-option ( the page where manager can choose either update category or add employees)
  - [x] product-related
  - [x] add-product
  - [x] search-product
  - [x] add-employee

**Comment by Jason897571** [comment]
All set up
