### ISSUE TITLE
Login Page - FRONT END

### ISSUE THREAD

**Issue by Rafflafressia** [Rafflafressia/Star-Inventory-Logistics#9]
This page should have two fields for username and password with a button. 

The button will have logic that will take a manager to the manger's product page, or a sales rep to the sales rep product page. 

Use two different dummy buttons one for manager and the other for sales

**Comment by bahman927** [comment]
I want to be working on Login-page, creating handlebars and all necessary task.

**Comment by bahman927** [comment]
1. I have finished layout of login page 
2. working on the logic of backend page 
3. need to add svg file on top of page

**Comment by bahman927** [comment]
I finshed working on login-handlebars and created a pull request.

**Comment by bahman927** [comment]
![Image](https://github.com/Rafflafressia/Star-Inventory-Logistics/assets/59753288/11895ff9-9743-45ce-ba59-6916d49d7e9e)
